<?php
    $catalogSearchHelper =  $this->helper('catalogsearch');
?>
<form id="search_mini_form" action="<?php echo $catalogSearchHelper->getResultUrl() ?>" method="get">
    <div class="input-append">
        <input id="appendedInputButton" 
               type="text" 
               name="<?php echo $catalogSearchHelper->getQueryParamName() ?>" 
               value="<?php echo $catalogSearchHelper->getEscapedQueryText() ?>" 
               class="span2" 
               maxlength="<?php echo $catalogSearchHelper->getMaxQueryLength();?>" 
               placeholder="Search" />
        <button type="submit" title="<?php echo $this->__('Search') ?>" 
                class="btn"><span><span><?php echo $this->__('Search') ?></span></span></button>
        <div id="search_autocomplete" class="search-autocomplete"></div>
        <script type="text/javascript">
        //<![CDATA[
            var searchForm = new Varien.searchForm('search_mini_form', 'search', '<?php echo $this->__('Search entire store here...') ?>');
            searchForm.initAutocomplete('<?php echo $catalogSearchHelper->getSuggestUrl() ?>', 'search_autocomplete');
        //]]>
        </script>
    </div>
</form>
