<?php $itemCounter = 0; ?>
<?php $allItems = $this->getItemCount(); ?>

<?php if ($this->getItemCount()): ?>
    <div class="crosssell">
        <h2><?php echo $this->__('Based on your selection, you may be interested in the following items:') ?></h2>

   <!-- my slider -->
<!--    
        <ul id="slider">
        <?php // foreach ($this->getItems() as $_item): ?>
            <li>
                <div class="flexible-cart-crosssell-item">
                    <a class="product-image" 
                       href="<?php // echo $_item->getProductUrl() ?>" 
                       title="<?php // echo $this->htmlEscape($_item->getName()) ?>">
                       <img src="<?php // echo $this->helper('catalog/image')
//                            ->init($_item, 'thumbnail');?>" 
                            alt="<?php // echo $this->htmlEscape($_item->getName()) ?>" />
                     </a>
                    <div class="product-details">
                        <h3 class="product-name"><a href="<?php // echo $_item->getProductUrl() ?>"><?php // echo $this->htmlEscape($_item->getName()) ?></a></h3>
                        <?php // echo $this->getPriceHtml($_item, true) ?>
                    </div>
                </div>
            </li>
        <?php // endforeach; ?>
        </ul>
        <div class="clearout"></div>-->

        
    <!--<script type="text/javascript">decorateList('crosssell-products-list', 'none-recursive')</script>-->
     <script type="text/javascript">
//        jQuery(window).load(function() {
//            jQuery("#slider").flexisel({
//            visibleItems: 3,
//            clone: false,
//            enableResponsiveBreakpoints: true,
//            responsiveBreakpoints: { 
//                portrait: { 
//                    changePoint:480,
//                    visibleItems: 1
//                }, 
//                landscape: { 
//                    changePoint:640,
//                    visibleItems: 2
//                },
//                tablet: { 
//                    changePoint:768,
//                    visibleItems: 3
//                }
//            }
//        })
//    });
    </script>
    </div>
<?php endif; ?>
