<?php $categories = Mage::helper('responsive/categories')->getCategories(); ?>

<div class="category-wrapper">
<p id="categorydivs"></p>   
<div class="home-categories-flex-parent-container">   
    <?php foreach ($categories as $category) : ?>
        <div class="home-categories-flex-item">
            <a href="<?php echo $category->getUrlPath(); ?>">
                <div class="category-name">
                    <p><h1><?php echo $category->name; ?><span>&raquo;</span></h1></p>
                </div>
                <figure class="category-image">
                    <?php if ($category->getImageUrl()) : ?>
                        <img class="img-polaroid" src="<?php echo $category->getImageUrl(); ?>" />
                    <?php else : ?>
                        <img class="img-polaroid" src="<?php echo $this->getSkinUrl('images/logo.gif'); ?>" />
                    <?php endif; ?>
                </figure>
            </a> 
        </div>
    <?php endforeach; ?>
</div>
</div>
