<header>
    <div class="header-flex-parent-container">
        <div class="header-flex-child-logo">
            <a href="<?php echo Mage::getUrl(); ?>">
                <img id="logo" src="<?php echo $this->getSkinUrl('images/logo_small.png'); ?>" 
                     alt="Logo" 
                     data-fullsrc="<?php echo $this->getSkinUrl('images/logo_tall.png'); ?>" />
            </a>
        </div>
        
        <div id="naviDiv" class="header-flex-child-nav">
            <div class="nav-menu-buttons">
                <a href="#menu-open" class="open-menu-button"><img src="<?php echo $this->getSkinUrl('images/menu_icon_tall_white.png'); ?>"/></a>
                <a href="#menu-close" class="close-menu-button"><img class="close-menu-button" src="<?php echo $this->getSkinUrl('images/menu_icon_tall_white.png'); ?>"/></a>
            </div>
            <nav class="toplinks-flex-parent-container"> 
                <?php echo $this->getChildHtml('topLinks') ?>
            </nav>
        </div>

        <div class="header-flex-child-cart">
            <a href="<?php echo Mage::getUrl(); ?>checkout/cart">
                <div id="cart-icon">
                    <img src="<?php echo $this->getSkinUrl('images/cart_icon_tall_white.png'); ?>" />
                    <span id="cart-text">Mein Warenkorb </span><span class="badge badge-important"><?php echo Mage::helper('checkout/cart')->getItemsCount(); ?></span>
                </div>
            </a>  
        </div>
    </div>

    <div class="search-flex-parent-container">
        <?php echo $this->getChildHtml('topSearch') ?>
    </div>
</header>
<script type="text/javascript">
    responsiveEnhance(document.getElementById('logo'), 100);
</script>