<script type="text/javascript">
jQuery(document).ready(function($){

	/* prepend menu icon */
	$('#nav-wrap').prepend('<div id="menu-icon"></div>');
	
	/* toggle nav */
	$("#naviDiv").on("click", function(){
		$(".top-links").slideToggle();
		$(this).toggleClass("active");
	});

});
</script>


<div class="header-flex-parent-container">
    <div class="header-flex-child-logo"><a href="<?php echo Mage::getUrl(); ?>">
        <img src="<?php echo $this->getSkinUrl('images/logo.gif'); ?>" />
    </a></div>

    <div id="naviDiv" class="header-flex-child-nav">
        <nav id="nav-wrap"> 
            <?php echo $this->getChildHtml('topLinks') ?>
        </nav>
    </div>

    <div class="header-flex-child-cart">
        <a href="<?php echo Mage::getUrl(); ?>checkout/cart">
            <div id="cart-icon">
                <img src="<?php echo $this->getSkinUrl('images/cart_icon_tall.png'); ?>" />
                <span id="cart-text">Mein Warenkorb </span><span class="badge badge-important"><?php echo Mage::helper('checkout/cart')->getItemsCount(); ?></span>
            </div>
        </a>  
    </div>
</div>

<div class="search-flex-parent-container">
    <?php echo $this->getChildHtml('topSearch') ?>
</div>