<?php $i = 0; ?>
<?php $images = Mage::helper('responsive/slider')->getSliderImages(); ?>
<div class="home-slider-wrapper">
    <figure class="carousel-figure">
        <div id="myCarousel" class="carousel slide">

            <!-- Indicators -->
            <ol class="carousel-indicators">
              <li data-target="#myCarousel" data-slide-to="0" class="active"></li>
              <li data-target="#myCarousel" data-slide-to="1"></li>
              <li data-target="#myCarousel" data-slide-to="2"></li>
            </ol>


            <div class="carousel-inner">
                <?php foreach ($images as $image) : ?>
                    <div class="item<?php if ($i == 0) : ?> active<?php endif; ?>" >
                    <img src="<?php echo $image; ?>" alt="">
                        <div class="container">
                            <div class="carousel-caption">
                                <h1>Example headline.</h1>
                            </div>
                        </div>
                    </div>   
                    <?php $i++; ?>
                <?php endforeach; ?>
            </div>

            <!-- Controls -->
            <a class="left carousel-control" href="#myCarousel" data-slide="prev">
                <span class="icon-prev"></span>
            </a>
            <a class="right carousel-control" href="#myCarousel" data-slide="next">
                <span class="icon-next"></span>
            </a>
        </div>
    </figure>

    <script type="text/javascript">
        $('#myCarousel').carousel({
          interval: 10000
        })
    </script>
</div>






















<?php //$rootCategories = Mage::helper('responsive/slider')->getRootCategories();
//$images = Mage::helper('responsive/slider')->getRandomCategoryProducts(); 
//var_dump($images); ?>

<!--<div class="home-slider">
    <div id="mi-slider" class="mi-slider">
        
        <?php //foreach($images as $categoryImages) : ?>
        <ul>
            <?php// foreach($categoryImages as $product) : ?>
                  <li>
                      <a href="<?php //echo $product->getProductUrl(); ?>">
                          <img src="<?php //echo $product->getImageUrl(); ?>">
                          <h4><?php //echo $product->name ?></h4>
                      </a>
                  </li>
            <?php //endforeach; ?>
        </ul>
        <?php //endforeach; ?>-->
        
        
        <!--
        <ul>
            <li><a href="#"><img src="<?php //echo $this->getSkinUrl('images/slider/1.jpg'); ?>" 
                                 alt="img01"><h4>Boots</h4></a></li>
            <li><a href="#"><img src="<?php //echo $this->getSkinUrl('images/slider/2.jpg'); ?>" alt="img02"><h4>Oxfords</h4></a></li>
            <li><a href="#"><img src="<?php //echo $this->getSkinUrl('images/slider/3.jpg'); ?>" alt="img03"><h4>Loafers</h4></a></li>
            <li><a href="#"><img src="<?php //echo $this->getSkinUrl('images/slider/4.jpg'); ?>" alt="img04"><h4>Sneakers</h4></a></li>
        </ul>
        <ul>
            <li><a href="#"><img src="<?php //echo $this->getSkinUrl('images/slider/5.jpg'); ?>" alt="img05"><h4>Belts</h4></a></li>
            <li><a href="#"><img src="<?php //echo $this->getSkinUrl('images/slider/6.jpg'); ?>" alt="img06"><h4>Hats & Caps</h4></a></li>
            <li><a href="#"><img src="<?php //echo $this->getSkinUrl('images/slider/7.jpg'); ?>" alt="img07"><h4>Sunglasses</h4></a></li>
            <li><a href="#"><img src="<?php //echo $this->getSkinUrl('images/slider/8.jpg'); ?>" alt="img08"><h4>Scarves</h4></a></li>
        </ul>
        <ul>
            <li><a href="#"><img src="<?php //echo $this->getSkinUrl('images/slider/9.jpg'); ?>" alt="img09"><h4>Casual</h4></a></li>
            <li><a href="#"><img src="<?php //echo $this->getSkinUrl('images/slider/10.jpg'); ?>" alt="img10"><h4>Luxury</h4></a></li>
            <li><a href="#"><img src="<?php //echo $this->getSkinUrl('images/slider/11.jpg'); ?>" alt="img11"><h4>Sport</h4></a></li>
        </ul>
        <ul>
            <li><a href="#"><img src="<?php //echo $this->getSkinUrl('images/slider/12.jpg'); ?>" alt="img12"><h4>Carry-Ons</h4></a></li>
            <li><a href="#"><img src="<?php //echo $this->getSkinUrl('images/slider/13.jpg'); ?>" alt="img13"><h4>Duffel Bags</h4></a></li>
            <li><a href="#"><img src="<?php //echo $this->getSkinUrl('images/slider/14.jpg'); ?>" alt="img14"><h4>Laptop Bags</h4></a></li>
            <li><a href="#"><img src="<?php //echo $this->getSkinUrl('images/slider/15.jpg'); ?>" alt="img15"><h4>Briefcases</h4></a></li>
        </ul>-->
        <!--<nav>
        <?php //foreach($rootCategories as $category) : ?>
            <a href="#"><?php //echo $category['name']; ?></a>
        <?php //endforeach;  ?>
        </nav>
    </div>


</div>
<script>
       /* $(function() {

                $( '#mi-slider' ).catslider();

        });*/
</script>-->
