<?php
/**
 * Template for Mage_Page_Block_Html
 */
?>
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Strict//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-strict.dtd">
<html xmlns="http://www.w3.org/1999/xhtml" xml:lang="<?php echo $this->getLang() ?>" lang="<?php echo $this->getLang() ?>">
<head>
<?php echo $this->getChildHtml('head') ?>
</head>
<body<?php echo $this->getBodyClass()?' class="'.$this->getBodyClass().'"':'' ?> id="menu-open">
    <div class="page-wrapper" id="menu-close">
   
    <!--<div class="row-fluid">
        <div class="span12">-->
            <?php echo $this->getChildHtml('header') ?>
        <!--</div>
    </div>-->
    
    <div class="home-slider-wrapper">
        <?php echo $this->getChildHtml('homeslider') ?>
    </div>
        <div class="category-wrapper">
        <p id="categorydivs"></p>
        <?php echo $this->getChildHtml('category-divs') ?>
    </div>
 <!--
    <div class="treemap-wrapper">
        <p id="categorytreemap"></p>
        <?php //echo $this->getChildHtml('treemap') ?>
    </div>
        
    <div class="div-treemap-wrapper">
        <?php //echo $this->getChildHtml('divtreemap') ?>
    </div>
        
    <div id="main">
        <?php //echo $this->getChildHtml('content') ?>
        <aside><?php //echo $this->getChildHtml('right') ?></aside>
    </div>-->
     
    <footer>
        <?php echo $this->getChildHtml('footer') ?>
        <?php echo $this->getChildHtml('before_body_end') ?>
    </footer>
 </div>
   <!--    
<?php //echo $this->getChildHtml('after_body_start') ?>
<div class="wrapper">
    <div class="page">
        
        <div class="row-fluid">
            <div class="span12">
                <?php //echo $this->getChildHtml('header') ?>
            </div>
        </div>
        <div class="row-fluid">
            <div class="span12">
                <p id="categorytreemap"></p>
                <?php //echo $this->getChildHtml('treemap') ?>
            </div>
        </div>
        
        <div class="row-fluid">
            <div class="span12">
                <p id="content"></p>
                <?php //echo $this->getChildHtml('content') ?>
                <aside>
            <?php //echo $this->getChildHtml('right') ?>
        </aside>
            </div>
        </div>
        
        
        
        <div class="row-fluid">
            <div class="span12">
                <div class="products" id=""></div>
            </div>
        </div>
        
        <div class="row-fluid">
            <div class="span12">
                
            </div>
        </div> 
    </div>
</div>
<?php //echo $this->getAbsoluteFooter() ?>
-->


</body>
</html>
