<?php
/**
 * Layout for index page. 
 * Without left and right sidebar.
 * Contains slider and category divs.
 */
?>

<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Strict//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-strict.dtd">
<html xmlns="http://www.w3.org/1999/xhtml" xml:lang="<?php echo $this->getLang() ?>" lang="<?php echo $this->getLang() ?>">
<head>
<?php echo $this->getChildHtml('head') ?>
</head>
<body<?php echo $this->getBodyClass()?' class="'.$this->getBodyClass().'"':'' ?>>
<?php echo $this->getChildHtml('after_body_start') ?>
<div class="wrapper">
    
    <?php echo $this->getChildHtml('global_notices') ?>
    <!-- header -->
    <?php echo $this->getChildHtml('header') ?>
    
    <div class="page">
        <section class="flexible-main-container-home">
            <!-- slider on home page -->
            <div class="home-slider-wrapper">
                <?php echo $this->getChildHtml('homeslider') ?>
            </div>
            <!-- category overview -->
            <div class="category-wrapper">
                <p id="categorydivs"></p>
                <?php echo $this->getChildHtml('category-divs') ?>
            </div>
            
            <?php echo $this->getChildHtml('global_messages') ?>
            <?php echo $this->getChildHtml('content') ?>
        </section>
    </div>
    
    <!-- footer -->
    <?php echo $this->getChildHtml('footer') ?>
    <?php echo $this->getChildHtml('before_body_end') ?>
</div>
<?php echo $this->getAbsoluteFooter() ?>
</body>
</html>
