<?php $_links = $this->getLinks(); ?>
<?php if(count($_links)>0): ?>
<!--<nav id="footer-links-wrapper">
    <ul id="footer-links-ul-->
<div class="footer-flex-parent-container">
        <?php foreach($_links as $_link): ?>
            <div class="footer-flex-item" <?php echo $_link->getLiParams() ?>><?php echo $_link->getBeforeText() ?><a href="<?php echo $_link->getUrl() ?>" title="<?php echo $_link->getTitle() ?>" <?php echo $_link->getAParams() ?>><?php echo $_link->getLabel() ?></a><?php echo $_link->getAfterText() ?></div>
        <?php endforeach; ?>
    <!--</ul>
</nav>-->
</div>   
<?php endif; ?>
