<div class="nav-open">
     <a href="#nav" title="Menü anzeigen">Ergebnisse filtern</a>
</div>

<?php if($this->canShowBlock()): ?>
<div id="nav" style="text-align: justify;">
    <div class="block block-layered-nav">
        <div class="block-title">
            <strong><span><?php echo $this->__('Shop By') ?></span></strong>
        </div>
        <div class="block-content">
            <?php echo $this->getStateHtml() ?>
            <?php if ($this->getLayer()->getState()->getFilters()): ?>
                <div class="actions"><a href="<?php echo $this->getClearUrl() ?>"><?php echo $this->__('Clear All') ?></a></div>
            <?php endif; ?>
            <?php if($this->canShowOptions()): ?>
                <p class="block-subtitle"><?php echo $this->__('Shopping Options') ?></p>
                <ul id="narrow-by-list">
                    
                    <?php $_filters = $this->getFilters() ?>
                    <?php foreach ($_filters as $_filter): ?>
                    <?php if($_filter->getItemsCount()): ?>
                        <li><?php echo $this->__($_filter->getName()) ?></li>
                    <?php endif; ?>
                    <?php endforeach; ?>
                        <li class="close"><a href="#">&uarr; Menü schließen</a></li>
                </ul>
                <script type="text/javascript">decorateDataList('narrow-by-list')</script>
            <?php endif; ?>
        </div>
    </div>
</div>
<?php endif; ?>
