<!-- button on category page for open off-canvas filter -->
<div class="filter-menu-trigger-selector" id="filter-menu-button-outside"
     style="display: none;">
  <div class="filter-inner">
      <label class="btn" for="toggle" onclick>&#62;&#62;  Ergebnisse filtern</label>
  </div>
</div>

<?php if($this->canShowBlock()): ?> 
<div id="filter-menu-selector" class="block block-layered-nav">
    <div class="block-title">
        <strong><span><?php echo $this->__('Shop By') ?></span></strong>
    </div>
    <div class="block-content">
        <?php echo $this->getStateHtml() ?>
        <?php if ($this->getLayer()->getState()->getFilters()): ?>
            <div class="actions"><a href="<?php echo $this->getClearUrl() ?>"><?php echo $this->__('Clear All') ?></a></div>
        <?php endif; ?>
        <?php if($this->canShowOptions()): ?>
            <p class="block-subtitle"><?php echo $this->__('Shopping Options') ?></p>
            <dl id="narrow-by-list">
                <?php $_filters = $this->getFilters() ?>
                <?php foreach ($_filters as $_filter): ?>
                <?php if($_filter->getItemsCount()): ?>
                    <dt><?php echo $this->__($_filter->getName()) ?></dt>
                    <dd><?php echo $_filter->getHtml() ?></dd>
                <?php endif; ?>
                <?php endforeach; ?>
            </dl>
            <script type="text/javascript">decorateDataList('narrow-by-list')</script>
        <?php endif; ?>
    </div>
    <!-- button on filter page for close off-canvas navigation -->
    <div class="filter-menu-trigger-selector">
        <div class="filter-inner">
            <label class="btn" for="toggle" onclick>Zurück</label>
        </div>
    </div>
</div>
<?php endif; ?>

<script type="text/javascript">
    if( jQuery(window).width() <= 1024 ){
        var jPM = jQuery.jPanelMenu({
            menu: '#filter-menu-selector',
            trigger: '.filter-menu-trigger-selector',
            afterOpen : function(){jQuery('#filter-menu-button-outside').css('display', 'none')},
            afterClose : function(){jQuery('#filter-menu-button-outside').css('display', 'block')},
        });
        jPM.on();
    }
</script>


