<?php if($this->getCollection()->getSize()): ?>

<div class="toolbar-flex-parent-container">
    
    <div class="toolbar-select-menus">
        <div class="limiter">
            <p><?php echo $this->__('Show') ?> <select onchange="setLocation(this.value)">
            <?php foreach ($this->getAvailableLimit() as  $_key=>$_limit): ?>
                <option value="<?php echo $this->getLimitUrl($_key) ?>"<?php if($this->isLimitCurrent($_key)): ?> selected="selected"<?php endif ?>>
                    <?php echo $_limit ?>
                </option>
            <?php endforeach; ?>
            </select> <?php echo $this->__('per page') ?></p>
        </div>

        <?php if( $this->isExpanded() ): ?>
        <div class="sorter">
            <div class="sort-by">
                <p>
                    <label><?php echo $this->__('Sort By') ?></label>
                    <select onchange="setLocation(this.value)">
                        <?php foreach($this->getAvailableOrders() as $_key=>$_order): ?>
                            <option value="<?php echo $this->getOrderUrl($_key, 'asc') ?>"<?php if($this->isOrderCurrent($_key)): ?> selected="selected"<?php endif; ?>>
                                <?php echo $this->__($_order) ?>
                            </option>
                        <?php endforeach; ?>
                    </select>
                <?php if($this->getCurrentDirection() == 'desc'): ?>
                    <a href="<?php echo $this->getOrderUrl(null, 'asc') ?>" title="<?php echo $this->__('Set Ascending Direction') ?>"><img src="<?php echo $this->getSkinUrl('images/i_desc_arrow.gif') ?>" alt="<?php echo $this->__('Set Ascending Direction') ?>" class="v-middle" /></a>
                <?php else: ?>
                    <a href="<?php echo $this->getOrderUrl(null, 'desc') ?>" title="<?php echo $this->__('Set Descending Direction') ?>"><img src="<?php echo $this->getSkinUrl('images/i_asc_arrow.gif') ?>" alt="<?php echo $this->__('Set Descending Direction') ?>" class="v-middle" /></a>
                <?php endif; ?></p>
            </div>
        </div>
        <?php endif; ?>
    </div>
    
    <p class="pages-amount">
        <?php if($this->getLastPageNum()>1): ?>
        <strong><?php echo $this->__('Items %s to %s of %s total', $this->getFirstNum(), $this->getLastNum(), $this->getTotalNum()) ?></strong>
        <?php else: ?>
            <strong><?php echo $this->__('Found Item(s): %s', $this->getTotalNum()) ?></strong>
        <?php endif; ?>
    </p>
    
    <div class="pager"><?php echo $this->getPagerHtml() ?></div>

    
</div>
<?php endif ?>
