<?php
    $_helper = $this->helper('catalog/output');
    $_product = $this->getProduct()
?>
<?php if($_additional = $this->getAdditionalData()): ?>
    <div id="product-additional-header">
        <span><?php echo $this->__('Additional Information') ?></span>
        <i id="additional-down-icon" class="icon-chevron-down"></i>
    </div>

    <table class="data-table" id="product-attribute-specs-table">
        <col width="25%" />
        <col />
        <tbody>
        <?php foreach ($_additional as $_data): ?>
            <tr>
                <th class="label"><?php echo $this->htmlEscape($this->__($_data['label'])) ?></th>
                <td class="data"><?php echo $_helper->productAttribute($_product, $_data['value'], $_data['code']) ?></td>
            </tr>
        <?php endforeach; ?>
        </tbody>
    </table>
    
    <script type="text/javascript">decorateTable('product-attribute-specs-table')</script>
    <script type="text/javascript">
        $('#additional-down-icon').click(function () {
            if ($('#product-attribute-specs-table').is(":hidden")) {
                $('#product-attribute-specs-table').slideDown("slow");
            } else {
                $('#product-attribute-specs-table').hide();
            }
        });
    </script>
<?php endif;?>
