<?php $_description = $this->getProduct()->getDescription(); ?>
<?php if ($_description): ?>

    <div id="product-description-header">
        <!--<h5><?php // echo $this->__('Details') ?></h5>-->
        <!--<i id="description-down-icon" class="icon-chevron-down"></i>-->
    </div>

    <div id="description-content-hidden">
        <?php echo $this->helper('catalog/output')->productAttribute($this->getProduct(), $_description, 'description') ?>
    </div>
    <script type="text/javascript">
        $('#description-down-icon').click(function() {
            if ($('#description-content-hidden').is(":hidden")) {
                $('#description-content-hidden').slideDown("slow");
            } else {
                $('#description-content-hidden').hide();
            }
        });
    </script>
<?php endif; ?>
