<?php
    $_product = $this->getProduct();
    $_helper = $this->helper('catalog/output');
?>
<script id="img-wrapper-tmpl" type="text/x-jquery-tmpl"> 
    <div class="rg-image-wrapper">
        
        <div class="rg-image"></div>
        <div class="rg-loading"></div>
        <div class="rg-caption-wrapper">
            <div class="rg-caption" style="display:none;">
                <p></p>
            </div>
        </div>
    </div>
</script>

<div id="rg-gallery" class="rg-gallery">
    <div class="rg-thumbs">
        <!-- Elastislide Carousel Thumbnail Viewer -->
        <div class="es-carousel-wrapper">
            <div class="es-nav">
                <span class="es-nav-prev">Previous</span>
                <span class="es-nav-next">Next</span>
            </div>
            <div class="es-carousel">
                <ul>
                    <li>
                        <a href="#">
                            <img src="<?php echo $this->helper('catalog/image')->init($_product, 'image'); ?>" 
                                 data-large="<?php echo $this->helper('catalog/image')->init($_product, 'image'); ?>" 
                                 alt="<?php echo $this->htmlEscape($this->getImageLabel()); ?>" 
                                 data-description="<?php echo $this->htmlEscape($this->getImageLabel()); ?>" />
                        </a>
                    </li>
                    <?php if (count($this->getGalleryImages()) > 0): ?>
                        <?php foreach ($this->getGalleryImages() as $_image): ?>
                            <li>
                                <a href="#">
                                    <img src="<?php echo $this->helper('catalog/image')->init($this->getProduct(), 'thumbnail', $_image->getFile())->resize(56); ?>" 
                                    data-large="<?php echo $this->htmlEscape($_image->getUrl()); ?>" 
                                    alt="<?php echo $this->htmlEscape($_image->getLabel()); ?>" 
                                    data-description="<?php echo $this->htmlEscape($_image->getLabel()); ?>" />
                                </a>
                            </li>
                        <?php endforeach; ?>
                    <?php endif; ?>
                </ul>
            </div>
        </div>
        <!-- End Elastislide Carousel Thumbnail Viewer -->
    </div><!-- rg-thumbs -->
</div><!-- rg-gallery -->


