<?php
    $_product = $this->getProduct();
    $_helper = $this->helper('catalog/output');
?>

<div id="my-slideshow">
    <div style="width: auto;">
  <ul class="bjqs">
    <li>
      <?php        
        echo '<img src="'.$this->helper('catalog/image')
                ->init($_product, 'image').
                '" alt="'.$this->htmlEscape($this->getImageLabel()).
                '" title="'.$this->htmlEscape($this->getImageLabel()).'" />';
    ?>
    </li>
    <?php if (count($this->getGalleryImages()) > 0): ?>
    <?php foreach ($this->getGalleryImages() as $_image): ?>
        <li>
            <img src="<?php echo $_image->url; ?>" />
        </li>
    <?php endforeach; ?>
    <?php endif; ?>
  </ul>
        </div>
</div>

<!-- Activate Slider for product images -->
<script class="secret-source">
        $(function() {
          $('#my-slideshow').bjqs({
            height      : 320,
            width       : 960,
            responsive  : true,
            usecaptions : false,
            nexttext : '>', 
            prevtext : '<'
          });
        });
</script>
