
<?php if ($this->getReviewsCount()): ?>
    <div class="ratings">
        <?php if ($this->getRatingSummary()):?>
            <div class="rating-box">
                <div class="rating" style="width:<?php echo $this->getRatingSummary() ?>%"></div>
            </div>
        <?php endif;?>
        
        
        <div class="rating-links">
            <a href="<?php echo $this->getReviewsUrl() ?>">
                <?php echo $this->__('%d Review(s)', $this->getReviewsCount()) ?>
            </a>
            <div class="add-review-icon">
                <a href="<?php echo $this->getReviewsUrl() ?>#review-form"><i id="new-review-icon" class="icon-plus-sign"></i></a>
            </div>
        </div>
    </div>
<?php elseif ($this->getDisplayIfEmpty()): ?>
    <h3><?php echo $this->__('Customer Reviews') ?></h3>
    <p class="no-rating"><a href="<?php echo $this->getReviewsUrl() ?>#review-form"><?php echo $this->__('Be the first to review this product') ?></a></p>
<?php endif; ?>

    
