
<?php if ($this->getReviewsCount()): ?>
    <div class="ratings">
        <?php if ($this->getRatingSummary()):?>
            <div class="rating-box">
                <div class="rating" style="width:<?php echo $this->getRatingSummary() ?>%"></div>
            </div>
        <?php endif;?>
        
        
        <div class="rating-links">
            <a href="<?php echo $this->getReviewsUrl() ?>">
                <?php echo $this->__('%d Review(s)', $this->getReviewsCount()) ?>
            </a>
            <img id="new-review-icon"
                 src="<?php echo $this->getSkinUrl('images/add_icon_tall.png');?>"/>
            <!--<div class="add-review-icon">
                 <a href="<?php // echo $this->getReviewsUrl() ?>#review-form"></a>
            </div>-->
        </div>
    </div>
<?php elseif ($this->getDisplayIfEmpty()): ?>
    <p class="no-rating"><a href="<?php echo $this->getReviewsUrl() ?>#review-form"><?php echo $this->__('Be the first to review this product') ?></a></p>
<?php endif; ?>

    
